version: "3"
services:
  react:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
    depends_on:
      - tests
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]
