FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object --legacy-peer-deps

COPY ./ ./

CMD ["npm","run","start"]